### ISSUE TITLE
Import menu doesn't appear?

### ISSUE THREAD

**Issue by applecuckoo** [Tiniifan/Level-5-blender-addon#2]
Hi! I wanted to rip some 3D models from Yo-Kai Watch and maybe even Yo-Kai Watch Blasters. Anyways, I installed the addon in Blender 4.0.2, enabled it and for whatever reason I can only find the Export menu, not the Import one.

**Comment by Tiniifan** [comment]
Hi.

The version of the addon available in release page doesn't have an import menu, 
the import menu will be available in the next update, if you want to read 3D models you have 2 solutions: 
- download the source of the addon [here](https://github.com/Tiniifan/Level-5-blender-addon) (click on code then download zip), which already contains the data for the next update, but be carefull: you may encounter some bugs.
- convert your model to .dae with Metanoia, which you can download [here](https://github.com/Tiniifan/Metanoia/releases/tag/LatestBuild), then you will be able to import your .dae with blender

**Comment by applecuckoo** [comment]
Thanks! I'm a Linux user so naturally the blender script would be better, but I'll stick with Metanoia and Bottles for now so I can use Blender's cleanup features on import. But the addon did work - here's a render of YKW1 Nate with Subdivision Surface applied:
![nate](https://github.com/Tiniifan/Level-5-blender-addon/assets/113647417/cbbafa30-3699-469b-a4fc-d7aa4d393191)

**Comment by Tiniifan** [comment]
Nice render
