### ISSUE TITLE
Problems with face mod 00 on .prm

### ISSUE THREAD

**Issue by applecuckoo** [Tiniifan/Level-5-blender-addon#3]
Hello! I tried opening the Forrester house (path is `data/map/e101i031/e101i031.xc` but I can only see a bunch of points around the scene. Textures were imported correctly.
![forresterhouse](https://github.com/Tiniifan/Level-5-blender-addon/assets/113647417/ac6744bc-ecc6-426d-9206-a8d61cc31971)

**Comment by Tiniifan** [comment]
Hi the points represent the meshes, the problem is the faces.
The addon can't get the faces or convert them in blender space. 
You should try metanoia

**Comment by Tiniifan** [comment]
I analyzed the problem .prm files (file who contains 3D data) have 2 modes for saving face data: 
- mode 00: which is just a list of triangle indices
- mode 02: which is a triangle strip index list
It seems that my code has a problem when mode 00 is used

**Comment by Tiniifan** [comment]
Fixed, but the map look so weird, I think it's a map that should only be used for an event, so it's not fully modeled so as not to consume memory
![image](https://github.com/Tiniifan/Level-5-blender-addon/assets/30804632/e3d0f2a8-1453-4440-ad74-14ede05d390f)

**Comment by Tiniifan** [comment]
thank you for reporting the problem, you can download the source that corrects this problem

**Comment by applecuckoo** [comment]
Oh okay that makes sense! Yeah, that was an event map. I've been using [this map list](https://ykw-modding.github.io/yo-docs/map-ids/ykw1-map-list.html) to check out certain locations. I apologise in advance if I'm about to file a lot of issues, but hey! At least it will help the project. 😃
